CREATE TABLE "account" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "account_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" integer NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "avatars" (
	"user_id" integer PRIMARY KEY NOT NULL,
	"bytes" "bytea" NOT NULL,
	"type" text NOT NULL,
	"updated_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "daily_metrics" (
	"user_id" integer NOT NULL,
	"day" date NOT NULL,
	"hrv_ms" double precision,
	"hrv_deep_ms" double precision,
	"rhr_bpm" double precision,
	"rhr_method" text,
	"resp_bpm" double precision,
	"nightly_temp_c" double precision,
	"spo2_pct" double precision,
	"vo2max_daily" double precision,
	"vo2max_run" double precision,
	"steps" integer,
	"calories" double precision,
	"weight_kg" double precision,
	"body_fat_pct" double precision,
	"hr_zones" jsonb,
	"light_moderate_min" double precision,
	"vigorous_peak_min" double precision,
	"temp_baseline_c" double precision,
	"temp_sd_c" double precision,
	"rhr_range_low" double precision,
	"rhr_range_high" double precision,
	"hrv_range_low" double precision,
	"hrv_range_high" double precision,
	"source" text NOT NULL,
	CONSTRAINT "daily_metrics_user_id_day_pk" PRIMARY KEY("user_id","day")
);
--> statement-breakpoint
CREATE TABLE "daily_scores" (
	"user_id" integer NOT NULL,
	"day" date NOT NULL,
	"scoring_version" integer NOT NULL,
	"strain" jsonb,
	"activities" jsonb,
	"session_rhr_bpm" double precision,
	"recovery" jsonb,
	"sleep" jsonb,
	"training_load" jsonb,
	"strain_target" jsonb,
	"sleep_planner" jsonb,
	"energy_bank" jsonb,
	"stress" jsonb,
	"health_monitor" jsonb,
	"healthspan" jsonb,
	"fitness" jsonb,
	"journal_impact" jsonb,
	CONSTRAINT "daily_scores_user_id_day_pk" PRIMARY KEY("user_id","day")
);
--> statement-breakpoint
CREATE TABLE "daily_values" (
	"user_id" integer NOT NULL,
	"day" text NOT NULL,
	"key" text NOT NULL,
	"value" double precision NOT NULL,
	CONSTRAINT "daily_values_user_id_day_key_pk" PRIMARY KEY("user_id","day","key")
);
--> statement-breakpoint
CREATE TABLE "dashboard_metrics" (
	"user_id" integer NOT NULL,
	"key" text NOT NULL,
	"position" integer NOT NULL,
	CONSTRAINT "dashboard_metrics_user_id_key_pk" PRIMARY KEY("user_id","key")
);
--> statement-breakpoint
CREATE TABLE "exercises" (
	"user_id" integer NOT NULL,
	"id" text NOT NULL,
	"day" date NOT NULL,
	"start_ts" bigint NOT NULL,
	"end_ts" bigint NOT NULL,
	"type" text NOT NULL,
	"name" text,
	"calories" double precision,
	"distance_m" double precision,
	"source" text NOT NULL,
	CONSTRAINT "exercises_user_id_id_pk" PRIMARY KEY("user_id","id")
);
--> statement-breakpoint
CREATE TABLE "health_records" (
	"user_id" integer NOT NULL,
	"id" text NOT NULL,
	"kind" text NOT NULL,
	"ts" bigint NOT NULL,
	"day" date NOT NULL,
	"data" jsonb NOT NULL,
	CONSTRAINT "health_records_user_id_id_pk" PRIMARY KEY("user_id","id")
);
--> statement-breakpoint
CREATE TABLE "hr_days" (
	"user_id" integer NOT NULL,
	"bucket" integer NOT NULL,
	"offsets" integer[] NOT NULL,
	"values" smallint[] NOT NULL,
	CONSTRAINT "hr_days_user_id_bucket_pk" PRIMARY KEY("user_id","bucket")
);
--> statement-breakpoint
CREATE TABLE "intraday_dirty" (
	"user_id" integer NOT NULL,
	"day" date NOT NULL,
	CONSTRAINT "intraday_dirty_user_id_day_pk" PRIMARY KEY("user_id","day")
);
--> statement-breakpoint
CREATE TABLE "intraday_series" (
	"user_id" integer NOT NULL,
	"day" date NOT NULL,
	"kind" text NOT NULL,
	"data" jsonb NOT NULL,
	CONSTRAINT "intraday_series_user_id_day_kind_pk" PRIMARY KEY("user_id","day","kind")
);
--> statement-breakpoint
CREATE TABLE "journal_entries" (
	"user_id" integer NOT NULL,
	"day" date NOT NULL,
	"tag" text NOT NULL,
	"value" integer NOT NULL,
	CONSTRAINT "journal_entries_user_id_day_tag_pk" PRIMARY KEY("user_id","day","tag")
);
--> statement-breakpoint
CREATE TABLE "journal_tags" (
	"user_id" integer NOT NULL,
	"tag" text NOT NULL,
	"label" text NOT NULL,
	"is_default" boolean DEFAULT false NOT NULL,
	"hidden" boolean DEFAULT false NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"seq" serial NOT NULL,
	CONSTRAINT "journal_tags_user_id_tag_pk" PRIMARY KEY("user_id","tag")
);
--> statement-breakpoint
CREATE TABLE "logged_entries" (
	"user_id" integer NOT NULL,
	"id" text NOT NULL,
	"type" text NOT NULL,
	"ts" bigint NOT NULL,
	"day" date NOT NULL,
	"data" jsonb NOT NULL,
	"google_name" text,
	"created_at" bigint NOT NULL,
	CONSTRAINT "logged_entries_user_id_id_pk" PRIMARY KEY("user_id","id")
);
--> statement-breakpoint
CREATE TABLE "oauth_tokens" (
	"user_id" integer PRIMARY KEY NOT NULL,
	"access_token" text NOT NULL,
	"refresh_token" text NOT NULL,
	"expires_at" bigint NOT NULL,
	"scope" text NOT NULL,
	"revoked_at" bigint,
	"updated_at" bigint NOT NULL,
	"google_email" text,
	"google_name" text,
	"google_picture" text
);
--> statement-breakpoint
CREATE TABLE "profile" (
	"user_id" integer PRIMARY KEY NOT NULL,
	"birth_date" date NOT NULL,
	"sex" text NOT NULL,
	"max_hr" integer,
	"height_cm" double precision,
	"time_zone" text NOT NULL,
	"updated_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rate_limit" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rate_limit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"key" text NOT NULL,
	"count" integer NOT NULL,
	"last_request" bigint NOT NULL,
	CONSTRAINT "rate_limit_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE "raw_payloads" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"type" text NOT NULL,
	"range_start" bigint NOT NULL,
	"range_end" bigint NOT NULL,
	"body_hash" text NOT NULL,
	"gz_body" "bytea" NOT NULL,
	"fetched_at" bigint NOT NULL,
	CONSTRAINT "raw_payloads_dedupe" UNIQUE("user_id","type","range_start","range_end","body_hash")
);
--> statement-breakpoint
CREATE TABLE "reports" (
	"user_id" integer NOT NULL,
	"period" text NOT NULL,
	"data" jsonb NOT NULL,
	CONSTRAINT "reports_user_id_period_pk" PRIMARY KEY("user_id","period")
);
--> statement-breakpoint
CREATE TABLE "session" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" integer NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "sleep_segments" (
	"user_id" integer NOT NULL,
	"session_id" text NOT NULL,
	"start_ts" bigint NOT NULL,
	"end_ts" bigint NOT NULL,
	"stage" text NOT NULL,
	CONSTRAINT "sleep_segments_user_id_session_id_start_ts_pk" PRIMARY KEY("user_id","session_id","start_ts")
);
--> statement-breakpoint
CREATE TABLE "sleep_sessions" (
	"user_id" integer NOT NULL,
	"id" text NOT NULL,
	"day" date NOT NULL,
	"start_ts" bigint NOT NULL,
	"end_ts" bigint NOT NULL,
	"is_main" boolean NOT NULL,
	"processed" boolean NOT NULL,
	"stages_status" text,
	"asleep_min" integer,
	"awake_min" integer,
	"deep_min" integer,
	"light_min" integer,
	"rem_min" integer,
	"source" text NOT NULL,
	CONSTRAINT "sleep_sessions_user_id_id_pk" PRIMARY KEY("user_id","id")
);
--> statement-breakpoint
CREATE TABLE "steps_days" (
	"user_id" integer NOT NULL,
	"bucket" integer NOT NULL,
	"offsets" integer[] NOT NULL,
	"values" integer[] NOT NULL,
	CONSTRAINT "steps_days_user_id_bucket_pk" PRIMARY KEY("user_id","bucket")
);
--> statement-breakpoint
CREATE TABLE "sync_state" (
	"user_id" integer NOT NULL,
	"type" text NOT NULL,
	"synced_through" bigint,
	"backfill_days_done" integer,
	"backfill_days_total" integer,
	"last_attempt_at" bigint,
	"last_success_at" bigint,
	"last_error" text,
	CONSTRAINT "sync_state_user_id_type_pk" PRIMARY KEY("user_id","type")
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"username" text,
	"display_username" text,
	CONSTRAINT "user_email_unique" UNIQUE("email"),
	CONSTRAINT "user_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "verification" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "verification_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "avatars" ADD CONSTRAINT "avatars_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_metrics" ADD CONSTRAINT "daily_metrics_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_scores" ADD CONSTRAINT "daily_scores_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_values" ADD CONSTRAINT "daily_values_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dashboard_metrics" ADD CONSTRAINT "dashboard_metrics_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "exercises" ADD CONSTRAINT "exercises_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "health_records" ADD CONSTRAINT "health_records_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hr_days" ADD CONSTRAINT "hr_days_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "intraday_dirty" ADD CONSTRAINT "intraday_dirty_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "intraday_series" ADD CONSTRAINT "intraday_series_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "journal_entries" ADD CONSTRAINT "journal_entries_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "journal_tags" ADD CONSTRAINT "journal_tags_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "logged_entries" ADD CONSTRAINT "logged_entries_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "oauth_tokens" ADD CONSTRAINT "oauth_tokens_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "profile" ADD CONSTRAINT "profile_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "raw_payloads" ADD CONSTRAINT "raw_payloads_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reports" ADD CONSTRAINT "reports_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sleep_segments" ADD CONSTRAINT "sleep_segments_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sleep_segments" ADD CONSTRAINT "sleep_segments_user_id_session_id_sleep_sessions_user_id_id_fk" FOREIGN KEY ("user_id","session_id") REFERENCES "public"."sleep_sessions"("user_id","id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sleep_sessions" ADD CONSTRAINT "sleep_sessions_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "steps_days" ADD CONSTRAINT "steps_days_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sync_state" ADD CONSTRAINT "sync_state_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_userId_idx" ON "account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "daily_values_key" ON "daily_values" USING btree ("user_id","key","day");--> statement-breakpoint
CREATE INDEX "exercises_day" ON "exercises" USING btree ("user_id","day");--> statement-breakpoint
CREATE INDEX "health_records_ts" ON "health_records" USING btree ("user_id","ts");--> statement-breakpoint
CREATE INDEX "logged_entries_ts" ON "logged_entries" USING btree ("user_id","ts");--> statement-breakpoint
CREATE INDEX "logged_entries_day_type" ON "logged_entries" USING btree ("user_id","day","type");--> statement-breakpoint
CREATE INDEX "raw_payloads_fetched_at" ON "raw_payloads" USING btree ("fetched_at");--> statement-breakpoint
CREATE INDEX "session_userId_idx" ON "session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "sleep_sessions_day" ON "sleep_sessions" USING btree ("user_id","day");--> statement-breakpoint
CREATE INDEX "verification_identifier_idx" ON "verification" USING btree ("identifier");